In [1]:
# Dependencies:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
# Locate the file
file = 'Resources/CAERS_ASCII_2004_2017Q2.csv'

In [3]:
# The correct encoding must be used to read the CSV in pandas
df = pd.read_csv(file, encoding="ISO-8859-1")

In [4]:
# Preview of the Dataframe
df.head(2)

,RA_Report #,RA_CAERS Created Date,AEC_Event Start Date,PRI_Product Role,PRI_Reported Brand/Product Name,PRI_FDA Industry Code,PRI_FDA Industry Name,CI_Age at Adverse Event,CI_Age Unit,CI_Gender,AEC_One Row Outcomes,SYM_One Row Coded Symptoms
0,65325,1/1/2004,8/4/2003,Suspect,MIDWEST COUNTRY FAIR CHOCOLATE FLAVORED CHIPS,3,Bakery Prod/Dough/Mix/Icing,2.0,Year(s),Female,"VISITED AN ER, VISITED A HEALTH CARE PROVIDER,...","SWELLING FACE, RASH, WHEEZING, COUGH, HOSPITAL..."
1,65325,1/1/2004,8/4/2003,Suspect,MIDWEST COUNTRY FAIR CHOCOLATE FLAVORED CHIPS,3,Bakery Prod/Dough/Mix/Icing,2.0,Year(s),Female,"VISITED AN ER, VISITED A HEALTH CARE PROVIDER,...","SWELLING FACE, WHEEZING, COUGH, RASH, HOSPITAL..."

In [5]:
# Drop all rows with missing information:
df = df.dropna(how='any')

In [6]:
# Verify dropped rows:
#df.count()

In [7]:
# Renaming the Columns:
df.columns = ['Report Num','Report Date','Event Start Date',
              'Product role','Producy Name','Industry','Industry Name',
              'Age','Age Unit','Gender','Outcomes','Side Effects']
df.head()

,Report Num,Report Date,Event Start Date,Product role,Producy Name,Industry,Industry Name,Age,Age Unit,Gender,Outcomes,Side Effects
0,65325,1/1/2004,8/4/2003,Suspect,MIDWEST COUNTRY FAIR CHOCOLATE FLAVORED CHIPS,3,Bakery Prod/Dough/Mix/Icing,2.0,Year(s),Female,"VISITED AN ER, VISITED A HEALTH CARE PROVIDER,...","SWELLING FACE, RASH, WHEEZING, COUGH, HOSPITAL..."
1,65325,1/1/2004,8/4/2003,Suspect,MIDWEST COUNTRY FAIR CHOCOLATE FLAVORED CHIPS,3,Bakery Prod/Dough/Mix/Icing,2.0,Year(s),Female,"VISITED AN ER, VISITED A HEALTH CARE PROVIDER,...","SWELLING FACE, WHEEZING, COUGH, RASH, HOSPITAL..."
3,65335,1/1/2004,11/24/2003,Suspect,ENFAMIL LIPIL BABY FORMULA,40,Baby Food Prod,3.0,Month(s),Not Available,NON-SERIOUS INJURIES/ ILLNESS,"GASTROINTESTINAL DISORDER, VOMITING"
5,65345,1/1/2004,12/21/2003,Suspect,"FRITO LAY FUNYUNS ONION FLAVOR, ONION RINGS",7,Snack Food Item,10.0,Year(s),Male,NON-SERIOUS INJURIES/ ILLNESS,CHOKING
16,65399,1/5/2004,11/22/2003,Suspect,METOBOLITE 356,54,Vit/Min/Prot/Unconv Diet(Human/Animal),51.0,Year(s),Male,DEATH,"COMPLETED SUICIDE, STRESS SYMPTOMS, DEATH"

In [8]:
df.describe()

          Report Num      Industry           Age
count   35428.000000  35428.000000  35428.000000
mean   159883.578102     45.561025     47.085893
std     38243.349070     15.172014     22.860219
min     65325.000000      2.000000      0.000000
25%    132809.000000     41.000000     31.000000
50%    171144.500000     54.000000     49.000000
75%    190784.000000     54.000000     64.000000
max    214516.000000     54.000000    736.000000

In [9]:
from pymongo import MongoClient

client = MongoClient()
col = client['test']['test']

data = df.to_dict(orient='records')
col.insert_many(data)

In [10]:
#Create connection to SQL Database
from sqlalchemy import create_engine
engine = create_engine('sqlite:///../Resources/adv_effects.sqlite', echo=False)

In [12]:
#Create new table in SQL DB
df.to_sql('adv_effects', con=engine)

OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)